
spring:
  application:
    name: webflux
  datasource:
    url: jdbc:mysql://localhost:3306/lecture?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 'eddy'
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    jdbc:
      dialect: maria