spring:
  application:
    name: spring-study-phase-2
  session:
    timeout: 120 # second
    redis:
      repository-type: default
  datasource:
    initialize: false
    driver-class-name:
    url: jdbc:mariadb://localhost:3306/study?serverTimezone=asia/seoul&characterEncoding=UTF-8
    username: root
    password: eddy
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost
server:
  servlet:
    session:
      timeout: 1800

logging:
  level:
    springstudy:
      session: debug
