spring:
  application:
    name: spring-study-phase-2
  session:
    timeout: 120 # second
    redis:
      repository-type: default
  datasource:
    initialize: false
    driver-class-name:
    url: jdbc:mariadb://localhost:3306/study?serverTimezone=asia/seoul&characterEncoding=UTF-8
    username: root
    password: eddy
  graphql:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-origin-patterns: "*"
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    schema:
      inspection:
        enabled: true
      printer:
        enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost
server:
  port: 8080
  servlet:
    session:
      timeout: 1800

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    springstudy: debug
