version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana
      - ./data/grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        ipv4_address: 172.18.0.2

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data/prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    networks:
      monitoring:
        ipv4_address: 172.18.0.3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "0:80" # 웹 서버 포트
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      monitoring:
        ipv4_address: 172.18.0.4

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113" # Nginx Exporter 포트
    environment:
      - NGINX_STATUS_URL=http://nginx/nginx_status
    networks:
      monitoring:
        ipv4_address: 172.18.0.5

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16