global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.18.0.3:9090']
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['172.18.0.5:9113']