version: "3.8"

services:
# Infra services
  mysql-master-a:
    image: mysql:8.4.3
    container_name: mysql-master-a
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: eddy
    volumes:
      - ./docker/mysql-master-a/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql-master-a/data:/var/lib/mysql

  mysql-master-b:
    image: mysql:8.4.3
    container_name: mysql-master-b
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: eddy
    volumes:
      - ./docker/mysql-master-b/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql-master-b/data:/var/lib/mysql

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - "3306:3306"
      - "8080:8080"  # HAProxy 웹 UI 포트
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
