version: "3.8"

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy-canary
    ports:
      - "80:80"
      - "8080:8080"  # HAProxy 웹 대시보드
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - canary-net

  web-app-v1:
    image: nginx:latest
    container_name: web-app-v1
    volumes:
      - ./docker/web-app-v1:/usr/share/nginx/html
    networks:
      - canary-net

  web-app-v2:
    image: nginx:latest
    container_name: web-app-v2
    volumes:
      - ./docker/web-app-v2:/usr/share/nginx/html
    networks:
      - canary-net

networks:
  canary-net:
    driver: bridge
