version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      app_network:
        ipv4_address: 172.18.0.2

  ubuntu-server:
    image: ubuntu:20.04
    container_name: ubuntu-server
    restart: always
    tty: true
    networks:
      app_network:
        ipv4_address: 172.18.0.3
    command: sleep infinity

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16