version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Jenkins에서 Docker 제어
    networks:
      app_network:
        ipv4_address: 172.18.0.2

  ubuntu-server:
    build:
      dockerfile: Dockerfile
    image: ubuntu:20.04
    container_name: ubuntu-server
    restart: always
    tty: true
    ports:
      - "3000:3000"
    networks:
      app_network:
        ipv4_address: 172.18.0.3
    command: sleep infinity

volumes:
  jenkins_home: {}

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16